id = "zed-pandoc-markdown"
name = "Pandoc Markdown"
version = "0.0.2"
schema_version = 1
authors = ["Yu Cong <sxlxcsxlxc@gmail.com>"]
description = "Pandoc Markdown language support"
repository = "https://github.com/sxlxc/zed-pandoc-markdown"
snippets = ["snippets/pandoc markdown.json"]

[language_servers.pandocmd]
name = "pandocmd"
languages = ["Pandoc Markdown"]

[grammars.pandoc_markdown]
repository = "https://github.com/sxlxc/tree-sitter-pandoc-markdown"
rev = "576f429913b3457f1c9cd1ef89f1fdaeca815840"
path = "tree-sitter-pandoc-markdown"

[grammars.pandoc_markdown_inline]
repository = "https://github.com/sxlxc/tree-sitter-pandoc-markdown"
rev = "576f429913b3457f1c9cd1ef89f1fdaeca815840"
path = "tree-sitter-pandoc-markdown-inline"
