id = "zed-pandoc-markdown"
name = "Pandoc Markdown"
version = "0.0.1"
schema_version = 1
authors = ["Yu Cong <sxlxcsxlxc@gmail.com>"]
description = "Pandoc Markdown language support"

[grammars.pandoc_markdown]
repository = "https://github.com/sxlxc/tree-sitter-pandoc-markdown"
rev = "059de0623d1f1edc2a08dcf31a32370513b93148"
path = "tree-sitter-pandoc-markdown"

[grammars.pandoc_markdown_inline]
repository = "https://github.com/sxlxc/tree-sitter-pandoc-markdown"
rev = "059de0623d1f1edc2a08dcf31a32370513b93148"
path = "tree-sitter-pandoc-markdown-inline"
